//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class entities : DbContext
    {
        private static entities _context;

        public static entities GetContext()
        {
            if (_context == null)
            {
                _context = new entities();
            }
            return _context;
        }

        public entities()
            : base("name=entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category1> Category1 { get; set; }
        public virtual DbSet<Discount1> Discount1 { get; set; }
        public virtual DbSet<Product1> Product1 { get; set; }
        public virtual DbSet<ProductSell> ProductSell { get; set; }
        public virtual DbSet<Role1> Role1 { get; set; }
        public virtual DbSet<Sell1> Sell1 { get; set; }
        public virtual DbSet<User1> User1 { get; set; }
    }
}
